name: Branch tagger

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name for the branch'
        required: true
        type: string

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Service Team token
        uses: navikt/github-app-token-generator@2d70c12368d1958155af4d283f9f21c9a2a8cb98
        id: get-service-token
        with:
          private-key: ${{ secrets.GIT_APP_PRIVATE_KEY }}
          app-id: ${{ secrets.GIT_APP_ID }}

      - name: Push tag
        id: tagging
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ steps.get-service-token.outputs.token }}
          custom_tag: "${{ inputs.tag }}"
          tag_prefix: ''
