name: On main

on:
  workflow_dispatch:
    inputs:
      forceappdispatch:
        description: "Force specific job dispatch for job"
        required: false
        type: choice
        options:
          - terraform
  push:
    branches:
      - main

jobs:
  # check what has changed
  filters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Filter
        uses: dorny/paths-filter@v2
        id: filters
        with:
          filters: |
            terraform:
              - 'infra/**'
              - 'refdata_deploy/**'
    outputs:
      terraform: ${{ steps.filters.outputs.terraform == 'true' && inputs.forceappdispatch == null }}

  terraform-apply-dev:
    needs: filters
    if: needs.filters.outputs.terraform == 'true' || inputs.forceappdispatch == 'terraform'
    uses: github-actions-library/.github/workflows/terraform.yml@main
    with:
      infra_dir_path: infra/
      target_env_name: dev
      aws_role_arn: "arn:aws:iam::3333333333:role/github"
      terraform_apply: true
      vault_role_id: 3333333333333333
      terraform_version: 1.3.7
      wiki_page_name: "TF dev"
    secrets:
      github_app_id: ${{ secrets.GITHUB_APP_ID }}
      github_app_private_key: ${{ secrets.GITHUB_PRIVATE_KEY }}
      team_github_app_id: ${{ secrets.TEAM_GIT_APP_ID }}
      team_github_app_private_key: ${{ secrets.TEAM_GIT_APP_PRIVATE_KEY }}
      teams_webhook: ${{ secrets.TEAMS_WEBHOOK }}
      vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
