name: On release (prod)

on:
  release:
    types: released

jobs:
  terraform-apply-prod:
    if: "!github.event.release.prerelease"
    uses: github-actions-library/.github/workflows/terraform.yml@main
    with:
      infra_dir_path: infra/
      target_env_name: prod
      aws_role_arn: "arn:aws:iam::333333333333:role/github"
      terraform_apply: true
      vault_role_id: 33333333333333
      terraform_version: 1.3.7
      python_version: '3.10'
    secrets:
      github_app_id: ${{ secrets.GITHUB_APP_ID }}
      github_app_private_key: ${{ secrets.GITHUB_PRIVATE_KEY }}
      team_github_app_id: ${{ secrets.TEAM_GIT_APP_ID }}
      team_github_app_private_key: ${{ secrets.TEAM_GIT_APP_PRIVATE_KEY }}
      teams_webhook: ${{ secrets.TEAMS_WEBHOOK }}
      vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}