name: On rc tag

on:
  push:
    tags:
      - v*.*.*-rc.*

jobs:
  terraform-apply-test-1:
    uses: github-actions-library/.github/workflows/terraform.yml@main
    with:
      infra_dir_path: infra/
      target_env_name: test-1
      aws_role_arn: "arn:aws:iam::3333333333333:role/github"
      terraform_apply: true
      vault_role_id: 3333333333333333333333333
      terraform_version: 1.3.7
      wiki_page_name: "TF test-1 ${{ github.ref_name }}"
    secrets:
      github_app_id: ${{ secrets.GITHUB_APP_ID }}
      github_app_private_key: ${{ secrets.GITHUB_PRIVATE_KEY }}
      team_github_app_id: ${{ secrets.TEAM_GIT_APP_ID }}
      team_github_app_private_key: ${{ secrets.TEAM_GIT_APP_PRIVATE_KEY }}
      teams_webhook: ${{ secrets.TEAMS_WEBHOOK }}
      vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
